/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms.views;

/**
 *
 * @author lionn
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        sidePanel = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnClasse = new javax.swing.JButton();
        btnEleve = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        sidePanel.setBackground(new java.awt.Color(0, 204, 204));
        sidePanel.setToolTipText("");
        sidePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI Light", 1, 36)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("TABLEAU DE BORD ");
        sidePanel.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 80, 410, 60));

        btnClasse.setBackground(new java.awt.Color(255, 255, 255));
        btnClasse.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnClasse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/class.png"))); // NOI18N
        btnClasse.setText("CLASSES");
        btnClasse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClasseActionPerformed(evt);
            }
        });
        sidePanel.add(btnClasse, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 290, 140));

        btnEleve.setBackground(new java.awt.Color(255, 255, 255));
        btnEleve.setFont(new java.awt.Font("Segoe UI Light", 1, 18)); // NOI18N
        btnEleve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/eleve.png"))); // NOI18N
        btnEleve.setText("ELEVES ");
        btnEleve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEleveActionPerformed(evt);
            }
        });
        sidePanel.add(btnEleve, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 290, 140));

        getContentPane().add(sidePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 860, 680));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClasseActionPerformed
        // TODO add your handling code here:
        Classes classe = new Classes();
        classe.setVisible(true);
        retour();
    }//GEN-LAST:event_btnClasseActionPerformed

    private void btnEleveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEleveActionPerformed
        // TODO add your handling code here
        Eleves eleve = new Eleves();
        eleve.setVisible(true);
        retour();
    }//GEN-LAST:event_btnEleveActionPerformed

     public void retour(){
        dispose();
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClasse;
    private javax.swing.JButton btnEleve;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel sidePanel;
    // End of variables declaration//GEN-END:variables
}
