/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sms.views;

import domaine.Classe;
import domaine.Eleve;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.AbstractAction;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import sms.Connecter;
import sms.DbHandler;

/**
 *
 * @author lionn
 */
public class Eleves extends javax.swing.JFrame {

    /**
     * Creates new form Classes
     */
    
    Connecter conn = new Connecter();
    Statement stm;
    ResultSet Rs;
    DefaultTableModel model =new DefaultTableModel();
    Eleve eleve = new Eleve();
    Classe classe = new Classe();
    DbHandler dao = new DbHandler();
    
    public void afficher(){
         try{
            stm = conn.obtenirConnexion().createStatement();
            ResultSet Rs = stm.executeQuery("SELECT matri,fname,lname,age,sex,phone,libelle FROM eleve INNER JOIN classe ON eleve.classe_id_class=classe.id_class");
            
            while(Rs.next()){
                model.addRow(new Object[]{
                    Rs.getString("matri"),
                    Rs.getString("fname"),
                    Rs.getString("lname"),
                    Rs.getString("age"),
                    Rs.getString("sex"),
                    Rs.getString("phone"),
                    Rs.getString("libelle"),
                });
            }
        }catch(Exception e){
            System.out.println(e);
        }
        
        tableEleve.setModel(model);
    }
    
    public Eleves() {
        initComponents();
        model.addColumn("MATRICULE");
        model.addColumn("NOM");
        model.addColumn("PRENOM");
        model.addColumn("AGE");
        model.addColumn("GENRE");
        model.addColumn("TELEPHONE");
        model.addColumn("Classe");
        
        afficher();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        searchPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        btnback = new javax.swing.JButton();
        actionPanel = new javax.swing.JPanel();
        btnAdd = new javax.swing.JToggleButton();
        btnEdit = new javax.swing.JToggleButton();
        btnDelete = new javax.swing.JToggleButton();
        btnClear1 = new javax.swing.JToggleButton();
        formPanel = new javax.swing.JPanel();
        label_nom = new javax.swing.JLabel();
        formPanel1 = new javax.swing.JPanel();
        label_prenom = new javax.swing.JLabel();
        et_prenom = new javax.swing.JTextField();
        label_age = new javax.swing.JLabel();
        et_age = new javax.swing.JTextField();
        label_sex = new javax.swing.JLabel();
        label_phone = new javax.swing.JLabel();
        label_classe = new javax.swing.JLabel();
        btnValider = new javax.swing.JToggleButton();
        et_nom = new javax.swing.JTextField();
        et_phone = new javax.swing.JTextField();
        cb_sex = new javax.swing.JComboBox<>();
        cb_classe = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        et_matri = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        resultPanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableEleve = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel1.setText("Recherche");

        btnback.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnback.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/back.png"))); // NOI18N
        btnback.setText("Retour");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout searchPanelLayout = new javax.swing.GroupLayout(searchPanel);
        searchPanel.setLayout(searchPanelLayout);
        searchPanelLayout.setHorizontalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnback, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(67, 67, 67)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(390, 390, 390))
        );
        searchPanelLayout.setVerticalGroup(
            searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, searchPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(searchPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnback)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(76, 76, 76))
            .addGroup(searchPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnAdd.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btnAdd.setText("Ajouter");
        btnAdd.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAddMouseClicked(evt);
            }
        });
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/modify.png"))); // NOI18N
        btnEdit.setText("Modifier");

        btnDelete.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/delete.png"))); // NOI18N
        btnDelete.setText("Supprimer");
        btnDelete.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDeleteMouseClicked(evt);
            }
        });
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnClear1.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnClear1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/update.png"))); // NOI18N
        btnClear1.setText("Clear");
        btnClear1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClear1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout actionPanelLayout = new javax.swing.GroupLayout(actionPanel);
        actionPanel.setLayout(actionPanelLayout);
        actionPanelLayout.setHorizontalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnAdd, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
                    .addComponent(btnClear1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        actionPanelLayout.setVerticalGroup(
            actionPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(actionPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEdit)
                .addGap(11, 11, 11)
                .addComponent(btnDelete)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClear1)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        label_nom.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        label_nom.setText("NOM");

        label_prenom.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        label_prenom.setText("PRENOM");

        et_prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_prenomActionPerformed(evt);
            }
        });

        label_age.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        label_age.setText("AGE");

        label_sex.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        label_sex.setText("SEX");

        label_phone.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        label_phone.setText("TÉLÉPHONE");

        label_classe.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        label_classe.setText("CLASSE");

        btnValider.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        btnValider.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/ok.png"))); // NOI18N
        btnValider.setText("Valider");

        et_nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_nomActionPerformed(evt);
            }
        });

        et_phone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                et_phoneActionPerformed(evt);
            }
        });

        cb_sex.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculin", "Feminin" }));

        cb_classe.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "TS1", "TS2", "PS1", "PS2", "TL1", "TL2", "PL1", "PL2", "S1", "S2", "L1", "L2" }));
        cb_classe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb_classeActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI Light", 1, 14)); // NOI18N
        jLabel2.setText("MATRICULE");

        javax.swing.GroupLayout formPanel1Layout = new javax.swing.GroupLayout(formPanel1);
        formPanel1.setLayout(formPanel1Layout);
        formPanel1Layout.setHorizontalGroup(
            formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanel1Layout.createSequentialGroup()
                .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanel1Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(btnValider, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(formPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(formPanel1Layout.createSequentialGroup()
                                .addComponent(label_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(et_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(et_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(formPanel1Layout.createSequentialGroup()
                                .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(formPanel1Layout.createSequentialGroup()
                                        .addComponent(label_age, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(46, 46, 46)))
                                .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(et_age, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                    .addComponent(et_matri, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE))))
                        .addGap(18, 18, 18)
                        .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(formPanel1Layout.createSequentialGroup()
                                .addComponent(label_classe, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(cb_classe, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPanel1Layout.createSequentialGroup()
                                .addComponent(label_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(et_phone, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPanel1Layout.createSequentialGroup()
                                .addComponent(label_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(63, 63, 63)
                                .addComponent(cb_sex, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(97, Short.MAX_VALUE))
        );
        formPanel1Layout.setVerticalGroup(
            formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanel1Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_sex)
                    .addComponent(et_nom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cb_sex, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(formPanel1Layout.createSequentialGroup()
                        .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(label_prenom)
                            .addComponent(label_phone)
                            .addComponent(et_phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, formPanel1Layout.createSequentialGroup()
                        .addComponent(et_prenom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(label_age)
                    .addComponent(label_classe)
                    .addComponent(cb_classe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(et_age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(formPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(et_matri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addComponent(btnValider)
                .addContainerGap(70, Short.MAX_VALUE))
        );

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout formPanelLayout = new javax.swing.GroupLayout(formPanel);
        formPanel.setLayout(formPanelLayout);
        formPanelLayout.setHorizontalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(label_nom, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(892, Short.MAX_VALUE))
            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(formPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(formPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(82, Short.MAX_VALUE)))
            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(formPanelLayout.createSequentialGroup()
                    .addGap(108, 108, 108)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(567, Short.MAX_VALUE)))
        );
        formPanelLayout.setVerticalGroup(
            formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formPanelLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(label_nom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(formPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(formPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(formPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(formPanelLayout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(257, Short.MAX_VALUE)))
        );

        tableEleve.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableEleve.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableEleveMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableEleve);

        javax.swing.GroupLayout resultPanelLayout = new javax.swing.GroupLayout(resultPanel);
        resultPanel.setLayout(resultPanelLayout);
        resultPanelLayout.setHorizontalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(resultPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        resultPanelLayout.setVerticalGroup(
            resultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, resultPanelLayout.createSequentialGroup()
                .addContainerGap(50, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(152, 152, 152))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(searchPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(searchPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(formPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(actionPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(resultPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 120, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void deplace(int i){
        try{
           et_nom.setText(model.getValueAt(i,1).toString()); 
           et_prenom.setText(model.getValueAt(i,2).toString()); 
           et_age.setText(model.getValueAt(i,3).toString());
           cb_sex.setSelectedItem(model.getValueAt(i,4).toString());
           et_phone.setText(model.getValueAt(i,5).toString()); 
           cb_classe.setSelectedItem(model.getValueAt(i,6).toString());
        }catch(Exception e){
            System.err.println(e);
            JOptionPane.showMessageDialog(null, "erreur de deplacement" +e.getLocalizedMessage());
        }
    }
    
    
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAddActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void et_nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_nomActionPerformed

    private void et_phoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_phoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_phoneActionPerformed

    private void cb_classeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb_classeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cb_classeActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        Dashboard db = new Dashboard();
        db.setVisible(true);
        retour();
    }//GEN-LAST:event_btnbackActionPerformed

    private void tableEleveMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableEleveMouseClicked
        // TODO add your handling code here:
        
        try{
            int i = tableEleve.getSelectedRow();
            deplace(i);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "erreur de deplacement" +e.getLocalizedMessage());
        }
    }//GEN-LAST:event_tableEleveMouseClicked

    private void btnAddMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAddMouseClicked
        // TODO add your handling code here:
        
        String nom = et_nom.getText();
        String prenom = et_prenom.getText();
        String age = et_age.getText();
        String sex = cb_sex.getSelectedItem().toString();
        
        if(nom ==""){
             JOptionPane.showMessageDialog(null, "Veuillez entrer le NOM de l'eleve SVP");
        }
        if(prenom ==""){
             JOptionPane.showMessageDialog(null, "Veuillez entrer le PRENOM de l'eleve SVP");
        }
        if(age ==""){
             JOptionPane.showMessageDialog(null, "Veuillez entrer l'AGE de l'eleve SVP");
        }
        
        if (sex=="Masculin"){
            sex = "M";
        }else{
            sex = "F";
        }
        String phone = et_phone.getText();
        String classe = cb_classe.getSelectedItem().toString();
        
        String requette = "INSERT into eleve(fname, lname,age, sex, phone, classe_id_class) VALUES('"+nom+"','"+prenom+"','"+age+"','"+sex+"','"+phone+"','"+classe+"')";
        
        
        String req = "INSERT into classe(id_class, libelle) VALUES ( '"+classe+"','"+classe+"')";
        
        try{
            stm.executeUpdate(requette);
            stm.executeUpdate(req);
            JOptionPane.showMessageDialog(null, "L'Eleve a bien été ajouté!");
            et_nom.setText("");
            et_prenom.setText("");
            et_age.setText("");
            et_phone.setText("");
            
            //afficher();
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e.getMessage());
        }
                
    }//GEN-LAST:event_btnAddMouseClicked

    private void btnClear1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClear1ActionPerformed
        // TODO add your handling code here:
        try{
            model.setRowCount(0);
            stm = conn.obtenirConnexion().createStatement();
            ResultSet Rs = stm.executeQuery("SELECT matri,fname,lname,age,sex,phone,libelle FROM eleve INNER JOIN classe ON eleve.classe_id_class=classe.id_class");
            
            while(Rs.next()){
                model.addRow(new Object[]{
                    Rs.getString("matri"),
                    Rs.getString("fname"),
                    Rs.getString("lname"),
                    Rs.getString("age"),
                    Rs.getString("sex"),
                    Rs.getString("phone"),
                    Rs.getString("libelle"),
                });
            }
        }catch(Exception e){
            System.out.println(e);
        }
        
        tableEleve.setModel(model);
        
    }//GEN-LAST:event_btnClear1ActionPerformed

    private void btnDeleteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDeleteMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnDeleteMouseClicked

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        try{
            stm = conn.obtenirConnexion().createStatement();
            String sqlParametre = "DELETE FROM smsdb.eleve WHERE eleve.matri=?";
            ResultSet Rs = stm.executeQuery(sqlParametre);
            
            while(Rs.next()){
                model.addRow(new Object[]{
                    Rs.getString("matri"),
                    Rs.getString("fname"),
                    Rs.getString("lname"),
                    Rs.getString("age"),
                    Rs.getString("sex"),
                    Rs.getString("phone"),
                    Rs.getString("libelle"),
                });
            }
        }catch(Exception e){
            System.out.println(e);
        }
        
        tableEleve.setModel(model);
        
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void et_prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_et_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_et_prenomActionPerformed

    public void retour(){
        dispose();
    }
   
        
public class GestionBoutons extends AbstractAction implements ActionListener {

        private static final long serialVersionUID = 1L;
        private boolean test = false;
        private String valueToFind = "";
        private String valueAt = "";
        int row;

        @Override
        public void actionPerformed(ActionEvent s) {

//            if (s.getSource() == btnDelete) {
//                modele.removeCustomer(tableEleve.getSelectedRow());
//            }

            if (s.getSource() == btnDelete) {
                
                et_nom.setEditable(true);
                et_prenom.setEditable(true);
                et_phone.setEditable(true);
                et_age.setEditable(true);
                cb_sex.setEnabled(true);
                cb_classe.setEnabled(true);
                btnValider.setEnabled(true);

                et_nom.setText((String) tableEleve.getValueAt(tableEleve.getSelectedRow(), 2));
                et_prenom.setText((String) tableEleve.getValueAt(tableEleve.getSelectedRow(), 1));
                et_phone.setText((String) tableEleve.getValueAt(tableEleve.getSelectedRow(), 3));
                et_age.setText((String) tableEleve.getValueAt(tableEleve.getSelectedRow(), 4));
                
            }

            if(s.getSource()== btnValider){

                
                eleve.setFname(et_nom.getText());
                eleve.setLname(et_prenom.getText());;
                eleve.setPhone(et_phone.getText());
                eleve.setAge(et_age.getText());
                eleve.setClasse((String) cb_classe.getSelectedItem());
                eleve.setSex((String) cb_sex.getSelectedItem());

                

                dao.update(eleve,classe);

                et_nom.setText("");
                et_prenom.setText("");
                et_phone.setText("");
                et_age.setText("");

              

                et_nom.setEditable(false);
                et_prenom.setEditable(false);
                et_phone.setEditable(false);
                et_age.setEditable(false);
                cb_classe.setEnabled(false);
                cb_sex.setEnabled(false);
                btnValider.setEnabled(false);
                
                
            }
            
            if(s.getSource()==btnClear1){

                et_nom.setText("");
               et_prenom.setText("");
               et_phone.setText("");
                et_age.setText("");

               

               et_nom.setEditable(false);
               et_prenom.setEditable(false);
                et_phone.setEditable(false);
                et_age.setEditable(false);
                cb_classe.setEnabled(false);
                cb_sex.setEnabled(false);
                btnValider.setEnabled(false);
            }
            
            
        }

    }


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Eleves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Eleves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Eleves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Eleves.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Eleves().setVisible(true);
            }
        });
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel actionPanel;
    private javax.swing.JToggleButton btnAdd;
    private javax.swing.JToggleButton btnClear1;
    private javax.swing.JToggleButton btnDelete;
    private javax.swing.JToggleButton btnEdit;
    private javax.swing.JToggleButton btnValider;
    private javax.swing.JButton btnback;
    private javax.swing.JComboBox<String> cb_classe;
    private javax.swing.JComboBox<String> cb_sex;
    private javax.swing.JTextField et_age;
    private javax.swing.JTextField et_matri;
    private javax.swing.JTextField et_nom;
    private javax.swing.JTextField et_phone;
    private javax.swing.JTextField et_prenom;
    private javax.swing.JPanel formPanel;
    private javax.swing.JPanel formPanel1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JLabel label_age;
    private javax.swing.JLabel label_classe;
    private javax.swing.JLabel label_nom;
    private javax.swing.JLabel label_phone;
    private javax.swing.JLabel label_prenom;
    private javax.swing.JLabel label_sex;
    private javax.swing.JPanel resultPanel;
    private javax.swing.JPanel searchPanel;
    private javax.swing.JTable tableEleve;
    // End of variables declaration//GEN-END:variables
}
